/**
 * Catálogo comercial de agentes de IA.
 *
 * Consolida os dois documentos de origem:
 *  - "Catálogo Oficial de Soluções — 50 Ideias de Agentes de IA" (10 categorias)
 *  - "Catálogo Completo de Agentes de IA — O Que, Como e Por Que" (4 blocos)
 *
 * Agentes que aparecem nos dois documentos foram unificados em uma única ficha
 * (o campo `fontes` registra a origem). Os textos de "o que faz", "como funciona"
 * e "objetivo" vêm dos documentos; áreas, dores, entregas, integrações e
 * palavras-chave são a classificação usada pela busca desta página.
 */

export const AREAS = [
  "Comercial",
  "Marketing e tráfego",
  "Atendimento",
  "Financeiro",
  "RH",
  "Operações",
  "Jurídico e compliance",
  "Diretoria",
] as const;

export type Area = (typeof AREAS)[number];

export const CATEGORIAS = [
  "Analistas",
  "Monitores",
  "Auditores",
  "Pesquisadores",
  "Estrategistas",
  "Gestores",
  "Orçamentos e propostas",
  "Documentos em PDF",
  "Concorrência",
  "Conteúdo e prospecção",
] as const;

export type Categoria = (typeof CATEGORIAS)[number];

export type CatalogAgent = {
  id: string;
  nome: string;
  categoria: Categoria;
  resumo: string;
  oQueFaz: string;
  /** Ausente quando o documento de origem não detalhou o funcionamento. */
  comoFunciona: string | null;
  objetivo: string;
  areas: Area[];
  dores: string[];
  entregas: string[];
  integracoes: string[];
  palavrasChave: string[];
  fontes: string[];
};

const C50 = (n: number) => `Catálogo 50 Agentes · #${n}`;
const CC = (n: number) => `Catálogo Completo · #${n}`;

export const AGENTS: CatalogAgent[] = [
  {
    id: "analista-roas",
    nome: "Analista de ROAS e performance de anúncios",
    categoria: "Analistas",
    resumo:
      "Vigia diariamente Meta e Google Ads, aponta criativos e públicos com CPA alto e avisa antes de queimar verba.",
    oQueFaz:
      "Analisa diariamente campanhas (Meta/Google) para identificar criativos e públicos com CPA elevado e monitora o desempenho dos anúncios em tempo real.",
    comoFunciona:
      "Integra-se via API às plataformas de anúncio, calcula tendências de queda de retorno, identifica anúncios com CPA alto ou CTR baixo e alerta o gestor ou pausa campanhas ruins automaticamente.",
    objetivo:
      "Evitar desperdício de verba com anúncios que não convertem e assegurar o ROAS planejado.",
    areas: ["Marketing e tráfego", "Diretoria"],
    dores: [
      "verba gasta sem retorno",
      "CPA subindo sem ninguém perceber",
      "campanha ruim rodando dias a fio",
    ],
    entregas: ["Alerta diário", "Relatório de performance", "Pausa automática de campanha"],
    integracoes: ["Meta Ads", "Google Ads", "APIs de anúncio"],
    palavrasChave: [
      "roas",
      "trafego pago",
      "anuncios",
      "ads",
      "cpa",
      "ctr",
      "verba",
      "campanha",
      "midia paga",
      "performance",
      "meta",
      "google",
      "facebook",
      "instagram",
    ],
    fontes: [C50(1), CC(6)],
  },
  {
    id: "analista-churn",
    nome: "Analista de churn preditivo",
    categoria: "Analistas",
    resumo:
      "Dá um score de risco de cancelamento para cada cliente da base antes que ele peça para sair.",
    oQueFaz: "Identifica clientes da base com alto risco de cancelamento antecipadamente.",
    comoFunciona:
      "Cruza dados do CRM, engajamento e histórico de suporte para calcular um score de risco por cliente.",
    objetivo: "Permitir retenção preventiva, preservando o LTV da base.",
    areas: ["Comercial", "Atendimento", "Diretoria"],
    dores: [
      "clientes cancelando sem aviso",
      "churn alto",
      "descobrir o problema tarde demais",
      "queda de receita recorrente",
    ],
    entregas: ["Score de risco", "Lista de clientes para retenção", "Alerta"],
    integracoes: ["CRM", "Banco de dados", "Histórico de suporte"],
    palavrasChave: [
      "churn",
      "cancelamento",
      "retencao",
      "ltv",
      "base de clientes",
      "recorrencia",
      "fidelizacao",
      "risco",
    ],
    fontes: [C50(2)],
  },
  {
    id: "analista-funil",
    nome: "Analista de gargalos no funil de vendas",
    categoria: "Analistas",
    resumo:
      "Mostra em qual etapa da pipeline as oportunidades travam e onde a conversão está vazando.",
    oQueFaz: "Examina onde as oportunidades estão estagnadas na pipeline do CRM.",
    comoFunciona:
      "Mapeia o tempo médio em cada etapa de vendas e aponta taxas desproporcionais de perda.",
    objetivo: "Otimizar a eficiência comercial e elevar a conversão final.",
    areas: ["Comercial", "Diretoria"],
    dores: [
      "negócios parados no funil",
      "conversão baixa",
      "não saber onde a venda trava",
      "pipeline inflada e sem fechamento",
    ],
    entregas: ["Diagnóstico do funil", "Relatório de conversão por etapa"],
    integracoes: ["CRM"],
    palavrasChave: [
      "funil",
      "pipeline",
      "conversao",
      "gargalo",
      "vendas",
      "etapa",
      "oportunidade",
      "comercial",
      "crm",
    ],
    fontes: [C50(3)],
  },
  {
    id: "analista-cvs",
    nome: "Analista de triagem de currículos (RH)",
    categoria: "Analistas",
    resumo:
      "Lê os currículos recebidos, compara com os requisitos da vaga e entrega os melhores perfis pontuados.",
    oQueFaz:
      "Avalia currículos comparando competências com a descrição exata da vaga e classifica os candidatos.",
    comoFunciona:
      "Extrai texto de PDFs, analisa experiências, compara com os requisitos obrigatórios e pontua a compatibilidade de cada candidato.",
    objetivo:
      "Reduzir em até 80% o tempo do RH na seleção inicial, encurtando a triagem de dias para segundos.",
    areas: ["RH"],
    dores: [
      "centenas de currículos para ler",
      "processo seletivo lento",
      "triagem manual demorada",
    ],
    entregas: ["Ranking de candidatos", "Score de aderência à vaga"],
    integracoes: ["OCR / leitura de PDF", "Banco de talentos", "E-mail"],
    palavrasChave: [
      "rh",
      "curriculo",
      "cv",
      "triagem",
      "recrutamento",
      "selecao",
      "candidato",
      "vaga",
      "contratacao",
      "pessoas",
    ],
    fontes: [C50(4), CC(14)],
  },
  {
    id: "analista-sentimento",
    nome: "Analista de sentimento do cliente",
    categoria: "Analistas",
    resumo:
      "Mede a temperatura da base lendo chats, e-mails e chamados — e avisa quando o clima azeda.",
    oQueFaz: "Mede a satisfação de clientes a partir de chats, e-mails e chamados.",
    comoFunciona: "Aplica Processamento de Linguagem Natural (NLP) no histórico de conversas.",
    objetivo: "Detectar crises de atendimento antecipadamente.",
    areas: ["Atendimento", "Diretoria"],
    dores: [
      "cliente insatisfeito que ninguém percebeu",
      "nota de satisfação caindo",
      "crise de atendimento",
    ],
    entregas: ["Índice de satisfação", "Alerta de crise"],
    integracoes: ["WhatsApp", "E-mail", "Help desk", "CRM"],
    palavrasChave: [
      "satisfacao",
      "sentimento",
      "nps",
      "reclamacao",
      "atendimento",
      "suporte",
      "chat",
      "cliente insatisfeito",
      "qualidade",
    ],
    fontes: [C50(5)],
  },
  {
    id: "monitor-uptime",
    nome: "Monitor de uptime e APIs operacionais",
    categoria: "Monitores",
    resumo:
      "Testa gateway de pagamento, APIs e sistemas a cada minuto e chama o time técnico na hora da queda.",
    oQueFaz: "Monitora a disponibilidade de gateways de pagamento, APIs e sistemas.",
    comoFunciona: "Dispara requisições contínuas testando endpoints essenciais a cada minuto.",
    objetivo: "Avisar a equipe técnica imediatamente sobre instabilidades.",
    areas: ["Operações"],
    dores: [
      "site ou checkout fora do ar sem ninguém saber",
      "pagamento falhando",
      "sistema instável",
    ],
    entregas: ["Alerta em tempo real", "Histórico de indisponibilidade"],
    integracoes: ["APIs internas", "Gateway de pagamento", "Slack / WhatsApp"],
    palavrasChave: [
      "uptime",
      "api",
      "sistema fora do ar",
      "instabilidade",
      "checkout",
      "pagamento",
      "monitoramento",
      "ti",
      "infraestrutura",
    ],
    fontes: [C50(6)],
  },
  {
    id: "monitor-orcamento-trafego",
    nome: "Monitor de orçamento diário de tráfego",
    categoria: "Monitores",
    resumo: "Controla a velocidade de queima da verba e impede o mês acabar no dia 12.",
    oQueFaz: "Controla a velocidade de consumo de verba em tempo real.",
    comoFunciona: "Compara o gasto acumulado ao longo do dia com o orçamento programado.",
    objetivo: "Impedir que as plataformas esgotem o orçamento mensal antecipadamente.",
    areas: ["Marketing e tráfego", "Financeiro"],
    dores: ["verba estourada antes do fim do mês", "gasto descontrolado em anúncios"],
    entregas: ["Alerta de estouro", "Acompanhamento diário de gasto"],
    integracoes: ["Meta Ads", "Google Ads"],
    palavrasChave: [
      "orcamento",
      "verba",
      "budget",
      "gasto",
      "trafego pago",
      "ads",
      "controle de custo",
      "midia",
    ],
    fontes: [C50(7)],
  },
  {
    id: "monitor-sla-whatsapp",
    nome: "Monitor de SLA de resposta no WhatsApp",
    categoria: "Monitores",
    resumo: "Cronometra quanto tempo o lead quente espera resposta e cobra o time antes de esfriar.",
    oQueFaz: "Acompanha o tempo de atendimento humano para leads qualificados.",
    comoFunciona:
      "Registra a chegada da mensagem e dispara alertas caso o prazo limite de resposta expire.",
    objetivo: "Garantir atendimento ágil no pico de intenção de compra.",
    areas: ["Atendimento", "Comercial"],
    dores: [
      "lead esperando resposta",
      "demora no atendimento",
      "lead esfria antes de alguém responder",
    ],
    entregas: ["Alerta de SLA estourado", "Relatório de tempo de resposta"],
    integracoes: ["WhatsApp", "CRM"],
    palavrasChave: [
      "whatsapp",
      "sla",
      "tempo de resposta",
      "atendimento",
      "lead",
      "demora",
      "resposta rapida",
      "comercial",
    ],
    fontes: [C50(8)],
  },
  {
    id: "monitor-reputacao",
    nome: "Monitor de menções e gestor de reputação",
    categoria: "Monitores",
    resumo:
      "Rastreia menções, comentários e avaliações da marca — e responde no tom certo antes da bola de neve.",
    oQueFaz:
      "Rastreia comentários, posts e menções sobre a empresa na internet e monitora avaliações de clientes em e-commerces e sites de review.",
    comoFunciona:
      "Escaneia APIs sociais e web scrapers buscando pelo nome da marca; ao detectar novas avaliações, redige respostas personalizadas mantendo o tom da marca e publica.",
    objetivo:
      "Proteger a reputação, interagir rapidamente com o público e fidelizar clientes antes que manchem a imagem da empresa.",
    areas: ["Marketing e tráfego", "Atendimento"],
    dores: [
      "avaliação ruim sem resposta",
      "reputação exposta na internet",
      "crise nas redes sociais",
    ],
    entregas: ["Alerta de menção", "Resposta publicada", "Relatório de reputação"],
    integracoes: ["Redes sociais", "Google Meu Negócio", "Reclame Aqui", "Web scraping"],
    palavrasChave: [
      "reputacao",
      "mencoes",
      "avaliacoes",
      "review",
      "redes sociais",
      "marca",
      "reclame aqui",
      "google meu negocio",
      "comentarios",
    ],
    fontes: [C50(9), CC(21)],
  },
  {
    id: "monitor-validade-documentos",
    nome: "Monitor de validade de documentos e certidões",
    categoria: "Monitores",
    resumo:
      "Controla vencimento de contratos, certidões e licenças com alertas regressivos de 60, 30 e 7 dias.",
    oQueFaz: "Controla prazos de vencimento de contratos, certidões e licenças.",
    comoFunciona: "Lê datas em bancos de dados ou PDFs e cria alertas regressivos (60, 30, 7 dias).",
    objetivo: "Evitar paralisações operacionais e multas regulatórias.",
    areas: ["Jurídico e compliance", "Operações"],
    dores: [
      "certidão vencida descoberta na hora errada",
      "contrato expirado sem renovação",
      "multa por documento fora do prazo",
    ],
    entregas: ["Alerta regressivo", "Calendário de vencimentos"],
    integracoes: ["Banco de dados", "Leitura de PDF", "Calendário"],
    palavrasChave: [
      "documento",
      "certidao",
      "licenca",
      "vencimento",
      "prazo",
      "contrato",
      "alvara",
      "regulatorio",
      "compliance",
    ],
    fontes: [C50(10)],
  },
  {
    id: "termometro-equipe",
    nome: "Termômetro de equipe",
    categoria: "Monitores",
    resumo: "Lê o clima interno de forma anônima e mostra ao RH qual time está sob pressão.",
    oQueFaz: "Monitora o clima organizacional de forma automatizada e anônima.",
    comoFunciona:
      "Coleta feedbacks voluntários e anônimos, analisa o tom emocional das mensagens e aponta ao RH quais departamentos estão sob estresse.",
    objetivo:
      "Permitir agir preventivamente antes de demissões em massa ou queda de produtividade.",
    areas: ["RH", "Diretoria"],
    dores: [
      "turnover alto",
      "equipe desmotivada",
      "clima organizacional ruim",
      "pedidos de demissão em sequência",
    ],
    entregas: ["Índice de clima por área", "Alerta ao RH"],
    integracoes: ["Formulários internos", "E-mail", "Chat interno"],
    palavrasChave: [
      "clima",
      "equipe",
      "rh",
      "turnover",
      "engajamento",
      "colaborador",
      "motivacao",
      "cultura",
      "demissao",
    ],
    fontes: [CC(19)],
  },
  {
    id: "auditor-crm",
    nome: "Auditor de regras de CRM",
    categoria: "Auditores",
    resumo: "Varre a pipeline e devolve a lista de negócios com campo vazio ou dado inconsistente.",
    oQueFaz: "Verifica se os vendedores preenchem os dados obrigatórios no CRM.",
    comoFunciona: "Varre negócios abertos sinalizando campos vazios ou inconsistentes.",
    objetivo: "Manter a base de dados comercial limpa e confiável.",
    areas: ["Comercial", "Diretoria"],
    dores: [
      "CRM desatualizado",
      "vendedor não preenche o sistema",
      "relatório comercial que ninguém confia",
    ],
    entregas: ["Lista de pendências por vendedor", "Alerta de inconsistência"],
    integracoes: ["CRM"],
    palavrasChave: [
      "crm",
      "dados",
      "preenchimento",
      "cadastro",
      "qualidade de dados",
      "vendedor",
      "processo comercial",
      "auditoria",
    ],
    fontes: [C50(11)],
  },
  {
    id: "auditor-ponto",
    nome: "Auditor de conformidade trabalhista e ponto (RH)",
    categoria: "Auditores",
    resumo: "Audita registros de ponto e horas extras e sinaliza o que pode virar passivo.",
    oQueFaz: "Audita registros de ponto e horas extras dos colaboradores.",
    comoFunciona: "Analisa logs buscando inconsistências ou horas extras não autorizadas.",
    objetivo: "Evitar passivos trabalhistas e cumprir a legislação.",
    areas: ["RH", "Jurídico e compliance"],
    dores: ["horas extras fora de controle", "risco trabalhista", "banco de horas bagunçado"],
    entregas: ["Relatório de inconsistências", "Alerta ao gestor"],
    integracoes: ["Sistema de ponto", "Folha de pagamento"],
    palavrasChave: [
      "ponto",
      "hora extra",
      "trabalhista",
      "rh",
      "clt",
      "jornada",
      "passivo",
      "folha",
      "conformidade",
    ],
    fontes: [C50(12)],
  },
  {
    id: "auditor-utm",
    nome: "Auditor de links de campanhas e UTMs",
    categoria: "Auditores",
    resumo: "Confere se todo anúncio no ar está com UTM correta antes de perder a mensuração.",
    oQueFaz: "Valida se todos os anúncios ativos contêm parâmetros UTM corretos.",
    comoFunciona: "Rastreia URLs finais checando a presença das tags de analytics.",
    objetivo: "Garantir mensuração precisa dos resultados de mídia.",
    areas: ["Marketing e tráfego"],
    dores: [
      "não saber de onde veio o lead",
      "relatório de mídia furado",
      "UTM errada ou faltando",
    ],
    entregas: ["Lista de anúncios com erro", "Relatório de rastreamento"],
    integracoes: ["Meta Ads", "Google Ads", "Google Analytics"],
    palavrasChave: [
      "utm",
      "rastreamento",
      "analytics",
      "mensuracao",
      "atribuicao",
      "link",
      "campanha",
      "trafego",
      "origem do lead",
    ],
    fontes: [C50(13)],
  },
  {
    id: "auditor-atendimento",
    nome: "Auditor de qualidade no atendimento",
    categoria: "Auditores",
    resumo: "Ouve as conversas do time e checa se o script e o padrão de atendimento foram seguidos.",
    oQueFaz: "Examina conversas entre atendentes e clientes checando scripts.",
    comoFunciona: "Analisa transcrições buscando termos obrigatórios e cordialidade.",
    objetivo: "Manter padrão de excelência no suporte e nas vendas.",
    areas: ["Atendimento", "Comercial"],
    dores: [
      "cada atendente fala de um jeito",
      "script não é seguido",
      "qualidade do atendimento sem controle",
    ],
    entregas: ["Nota por atendimento", "Relatório de aderência ao script"],
    integracoes: ["WhatsApp", "Help desk", "Gravações e transcrições"],
    palavrasChave: [
      "atendimento",
      "script",
      "qualidade",
      "monitoria",
      "suporte",
      "call center",
      "padrao",
      "treinamento",
      "transcricao",
    ],
    fontes: [C50(14)],
  },
  {
    id: "auditor-despesas",
    nome: "Auditor de notas fiscais, despesas e reembolsos",
    categoria: "Auditores",
    resumo:
      "Lê o comprovante por OCR, cruza com a política da empresa e aprova ou manda para exceção.",
    oQueFaz:
      "Compara comprovantes de despesas com notas fiscais e políticas internas e faz a validação prévia de reembolsos corporativos.",
    comoFunciona:
      "Lê recibos por OCR, cruza valores com os extratos informados e confronta valor e categoria com a política da empresa: aprova gastos regulares ou encaminha exceções.",
    objetivo:
      "Evitar pagamentos duplicados, fraudes e estouros de teto, agilizando o fluxo de caixa interno.",
    areas: ["Financeiro", "Operações"],
    dores: [
      "reembolso demorado",
      "despesa fora da política",
      "pagamento duplicado",
      "nota fiscal conferida na mão",
    ],
    entregas: ["Aprovação automática", "Fila de exceções", "Relatório de despesas"],
    integracoes: ["OCR", "ERP", "Extrato bancário", "Planilhas"],
    palavrasChave: [
      "despesa",
      "reembolso",
      "nota fiscal",
      "financeiro",
      "recibo",
      "fraude",
      "ocr",
      "conferencia",
      "politica de gastos",
    ],
    fontes: [C50(15), CC(18)],
  },
  {
    id: "auditor-processos",
    nome: "Auditor de processos e compliance",
    categoria: "Auditores",
    resumo: "Fiscaliza se as regras internas estão sendo cumpridas e avisa o gestor no desvio.",
    oQueFaz: "Fiscaliza se as regras internas e os regulamentos estão sendo seguidos.",
    comoFunciona:
      "Analisa logs de atendimento e transações, identifica desvios ou falhas no padrão e emite alerta para o gestor responsável.",
    objetivo: "Prevenir falhas operacionais graves, multas e problemas jurídicos.",
    areas: ["Operações", "Jurídico e compliance", "Diretoria"],
    dores: [
      "processo interno que ninguém segue",
      "falha operacional recorrente",
      "risco de multa",
    ],
    entregas: ["Alerta de desvio", "Relatório de conformidade"],
    integracoes: ["Sistemas internos", "Logs de atendimento", "ERP"],
    palavrasChave: [
      "compliance",
      "processo",
      "auditoria",
      "regra interna",
      "desvio",
      "governanca",
      "operacao",
      "padronizacao",
    ],
    fontes: [CC(15)],
  },
  {
    id: "auditor-lgpd",
    nome: "Auditor de LGPD",
    categoria: "Auditores",
    resumo: "Procura CPF, senha e dado bancário circulando onde não deveria e avisa a TI.",
    oQueFaz: "Protege a empresa contra vazamentos de dados sensíveis.",
    comoFunciona:
      "Escaneia e-mails, chats e arquivos buscando CPFs, senhas ou dados bancários expostos e sinaliza os pontos de risco para a TI.",
    objetivo: "Garantir conformidade com a LGPD e evitar multas pesadas.",
    areas: ["Jurídico e compliance", "Operações"],
    dores: ["dado sensível exposto", "risco de multa da LGPD", "vazamento de informação"],
    entregas: ["Mapa de risco", "Alerta para a TI"],
    integracoes: ["E-mail", "Chat interno", "Repositórios de arquivos"],
    palavrasChave: [
      "lgpd",
      "dados pessoais",
      "privacidade",
      "vazamento",
      "seguranca",
      "cpf",
      "compliance",
      "juridico",
    ],
    fontes: [CC(17)],
  },
  {
    id: "pesquisador-icp",
    nome: "Pesquisador de ICP e lead scoring",
    categoria: "Pesquisadores",
    resumo:
      "Enriquece cada lead novo com dados públicos de porte e faturamento e entrega só quem tem perfil de compra.",
    oQueFaz: "Enriquece os dados de novas empresas que entram no funil comercial.",
    comoFunciona:
      "Rastreia site, LinkedIn e fontes públicas em busca de faturamento, porte e demais sinais de perfil.",
    objetivo: "Entregar ao comercial apenas leads com real perfil de compra.",
    areas: ["Comercial", "Marketing e tráfego"],
    dores: [
      "time perdendo tempo com lead ruim",
      "não saber quem é o lead que chegou",
      "prospecção sem critério",
    ],
    entregas: ["Ficha enriquecida do lead", "Score de aderência ao ICP"],
    integracoes: ["CRM", "LinkedIn", "Web scraping", "Fontes públicas"],
    palavrasChave: [
      "icp",
      "lead scoring",
      "qualificacao",
      "enriquecimento",
      "b2b",
      "prospeccao",
      "perfil de cliente",
      "lead",
      "porte",
    ],
    fontes: [C50(16)],
  },
  {
    id: "pesquisador-tendencias",
    nome: "Pesquisador e caçador de tendências",
    categoria: "Pesquisadores",
    resumo:
      "Varre buscas, fóruns e redes atrás de assunto quente do nicho e avisa enquanto a onda está subindo.",
    oQueFaz:
      "Busca temas relevantes e notícias quentes sobre o nicho da empresa e monitora picos de interesse na internet para aproveitar o timing de mercado.",
    comoFunciona:
      "Varre Google Trends, fóruns, portais de notícias e redes sociais diariamente, identifica memes, notícias ou dores emergentes e envia alerta com sugestões de posicionamento.",
    objetivo:
      "Alimentar o marketing com insights sobre o público-alvo e permitir surfar ondas virais rapidamente, gerando tráfego orgânico.",
    areas: ["Marketing e tráfego"],
    dores: [
      "falta de assunto para postar",
      "perder o timing de um tema quente",
      "conteúdo sempre atrasado",
    ],
    entregas: ["Alerta de tendência", "Lista de pautas"],
    integracoes: ["Google Trends", "Redes sociais", "Portais de notícia", "Fóruns"],
    palavrasChave: [
      "tendencia",
      "trend",
      "pauta",
      "conteudo",
      "viral",
      "noticia",
      "mercado",
      "insight",
      "timing",
    ],
    fontes: [C50(17), CC(10)],
  },
  {
    id: "pesquisador-regulamentacoes",
    nome: "Pesquisador de regulamentações e leis",
    categoria: "Pesquisadores",
    resumo: "Acompanha diários oficiais e avisa quando muda alguma regra que afeta a operação.",
    oQueFaz: "Acompanha alterações contratuais, fiscais ou regulatórias do setor.",
    comoFunciona: "Monitora diários oficiais em busca de palavras-chave do setor.",
    objetivo: "Manter a operação jurídica e tributária sempre atualizada.",
    areas: ["Jurídico e compliance", "Financeiro"],
    dores: [
      "mudança na lei descoberta tarde",
      "risco fiscal",
      "setor muito regulado",
    ],
    entregas: ["Alerta regulatório", "Resumo da mudança"],
    integracoes: ["Diários oficiais", "Portais do governo"],
    palavrasChave: [
      "lei",
      "regulamentacao",
      "juridico",
      "fiscal",
      "tributario",
      "norma",
      "diario oficial",
      "legislacao",
      "compliance",
    ],
    fontes: [C50(18)],
  },
  {
    id: "pesquisador-tecnologias",
    nome: "Pesquisador de tecnologias para processos",
    categoria: "Pesquisadores",
    resumo: "Mapeia ferramentas de mercado que resolvem um gargalo interno, com preços e reviews.",
    oQueFaz: "Mapeia ferramentas de mercado para automatizar etapas internas.",
    comoFunciona: "Pesquisa plataformas SaaS, lê reviews e sintetiza planos de preços.",
    objetivo: "Evoluir a infraestrutura com as melhores tecnologias.",
    areas: ["Operações", "Diretoria"],
    dores: [
      "processo manual sem ferramenta",
      "não saber qual sistema contratar",
      "stack defasada",
    ],
    entregas: ["Comparativo de ferramentas", "Resumo de preços"],
    integracoes: ["Web scraping", "Sites de review"],
    palavrasChave: [
      "ferramenta",
      "saas",
      "tecnologia",
      "automacao",
      "sistema",
      "software",
      "processo interno",
      "comparativo",
    ],
    fontes: [C50(19)],
  },
  {
    id: "pesquisador-candidatos",
    nome: "Pesquisador de candidatos ativos (sourcing RH)",
    categoria: "Pesquisadores",
    resumo: "Caça profissionais para vagas técnicas difíceis em redes e repositórios públicos.",
    oQueFaz: "Encontra profissionais alinhados a vagas técnicas complexas.",
    comoFunciona: "Executa buscas avançadas em redes profissionais e repositórios.",
    objetivo: "Acelerar a captação de talentos para o recrutamento.",
    areas: ["RH"],
    dores: ["vaga técnica parada", "poucos candidatos qualificados", "recrutamento lento"],
    entregas: ["Lista de candidatos", "Ficha do profissional"],
    integracoes: ["LinkedIn", "GitHub", "Portais de vagas"],
    palavrasChave: [
      "sourcing",
      "recrutamento",
      "talento",
      "vaga",
      "candidato",
      "rh",
      "hunting",
      "linkedin",
      "tecnica",
    ],
    fontes: [C50(20)],
  },
  {
    id: "estrategista-verba",
    nome: "Estrategista de redistribuição de verba de tráfego",
    categoria: "Estrategistas",
    resumo: "Simula cenários e recomenda para onde levar o orçamento entre canais de mídia.",
    oQueFaz: "Recomenda realocações de orçamento entre canais de mídia.",
    comoFunciona: "Simula cenários com base no histórico de ROAS de cada plataforma.",
    objetivo: "Maximizar o volume de conversões sem elevar o orçamento.",
    areas: ["Marketing e tráfego", "Diretoria"],
    dores: [
      "verba mal distribuída entre canais",
      "não saber onde investir mais",
      "conversão estagnada",
    ],
    entregas: ["Recomendação de realocação", "Simulação de cenários"],
    integracoes: ["Meta Ads", "Google Ads", "Planilhas"],
    palavrasChave: [
      "verba",
      "orcamento",
      "canal",
      "roas",
      "midia",
      "investimento",
      "trafego pago",
      "alocacao",
      "conversao",
    ],
    fontes: [C50(21)],
  },
  {
    id: "estrategista-cross-sell",
    nome: "Estrategista de venda cruzada (cross-sell e up-sell)",
    categoria: "Estrategistas",
    resumo: "Aponta o produto certo e a hora certa de oferecer mais para quem já é cliente.",
    oQueFaz: "Recomenda o momento e o produto ideal para ofertar a clientes ativos.",
    comoFunciona: "Estuda o histórico de compras e o padrão de uso da solução.",
    objetivo: "Expandir o faturamento por cliente sem custo de aquisição.",
    areas: ["Comercial", "Diretoria"],
    dores: [
      "ticket médio parado",
      "base grande e pouca recompra",
      "vender mais sem gastar em anúncio",
    ],
    entregas: ["Lista de oportunidades por cliente", "Recomendação de oferta"],
    integracoes: ["CRM", "ERP", "Histórico de compras"],
    palavrasChave: [
      "cross sell",
      "up sell",
      "venda cruzada",
      "ticket medio",
      "recompra",
      "base de clientes",
      "faturamento",
      "expansao",
    ],
    fontes: [C50(22)],
  },
  {
    id: "estrategista-cadencia",
    nome: "Estrategista de cadência de prospecção (outbound)",
    categoria: "Estrategistas",
    resumo: "Define quantos contatos e em que intervalo a régua outbound deve ter para converter.",
    oQueFaz: "Define a quantidade e o intervalo ideal de contatos nas réguas de outbound.",
    comoFunciona: "Analisa taxas de abertura e resposta para otimizar as sequências.",
    objetivo: "Aumentar agendamentos de reuniões sem gerar incômodo.",
    areas: ["Comercial"],
    dores: [
      "prospecção sem resposta",
      "cadência mal calibrada",
      "poucas reuniões agendadas",
    ],
    entregas: ["Régua de contatos otimizada", "Relatório de resposta"],
    integracoes: ["CRM", "E-mail", "WhatsApp", "Ferramentas de cadência"],
    palavrasChave: [
      "outbound",
      "cadencia",
      "prospeccao",
      "regua",
      "follow up",
      "reuniao",
      "sdr",
      "sequencia",
      "b2b",
    ],
    fontes: [C50(23)],
  },
  {
    id: "estrategista-precificacao",
    nome: "Estrategista de precificação dinâmica",
    categoria: "Estrategistas",
    resumo: "Sugere ajuste de preço olhando custo, demanda atual e o que o mercado está praticando.",
    oQueFaz: "Sugere ajustes nos preços de produtos com base em oferta e demanda.",
    comoFunciona: "Analisa custos, demanda atual e valores praticados no mercado.",
    objetivo: "Otimizar a margem de lucro conforme as oportunidades.",
    areas: ["Comercial", "Financeiro", "Diretoria"],
    dores: ["preço desatualizado", "margem apertada", "desconto dado no chute"],
    entregas: ["Sugestão de preço", "Relatório de margem"],
    integracoes: ["ERP", "Planilhas", "Sites de concorrentes"],
    palavrasChave: [
      "preco",
      "precificacao",
      "margem",
      "desconto",
      "lucro",
      "tabela",
      "mercado",
      "demanda",
      "custo",
    ],
    fontes: [C50(24)],
  },
  {
    id: "estrategista-reativacao",
    nome: "Estrategista de reativação de base inativa e carrinhos",
    categoria: "Estrategistas",
    resumo:
      "Segmenta ex-clientes e abandonos de checkout e conduz a volta com oferta e mensagem sob medida.",
    oQueFaz:
      "Planeja campanhas com ofertas customizadas para ex-clientes e recupera quem abandonou o checkout ou parou de responder.",
    comoFunciona:
      "Segmenta os motivos de perda antiga criando ganchos específicos; com gatilho de tempo acionado, dispara mensagem empática oferecendo suporte ou incentivo e conduz a conversa caso o cliente responda.",
    objetivo:
      "Gerar receita nova aproveitando contatos antigos e tráfego já pago, dados como perdidos.",
    areas: ["Comercial", "Marketing e tráfego"],
    dores: [
      "base parada sem faturar",
      "carrinho abandonado",
      "lead frio esquecido",
      "cliente que sumiu",
    ],
    entregas: ["Campanha segmentada", "Mensagem automática", "Fila de reativação"],
    integracoes: ["CRM", "WhatsApp", "E-mail", "E-commerce"],
    palavrasChave: [
      "reativacao",
      "base inativa",
      "carrinho abandonado",
      "lead frio",
      "ex cliente",
      "recuperacao",
      "campanha",
      "remarketing",
    ],
    fontes: [C50(25), CC(4)],
  },
  {
    id: "estrategista-conteudo",
    nome: "Estrategista de conteúdo",
    categoria: "Estrategistas",
    resumo: "Monta o calendário editorial da semana e já entrega os rascunhos de legenda e roteiro.",
    oQueFaz: "Planeja pautas, temas e rascunhos de postagens baseados em tendências.",
    comoFunciona:
      "Analisa termos buscados e dúvidas do suporte, cria o calendário editorial semanal e redige rascunhos iniciais de legendas e roteiros.",
    objetivo:
      "Manter a constância e a autoridade da marca nas redes sociais sem exigir horas de planejamento manual.",
    areas: ["Marketing e tráfego"],
    dores: [
      "rede social parada",
      "falta de constância nas postagens",
      "planejamento de conteúdo consome o time",
    ],
    entregas: ["Calendário editorial", "Rascunhos de post e roteiro"],
    integracoes: ["Redes sociais", "Google Trends", "Help desk"],
    palavrasChave: [
      "conteudo",
      "social media",
      "post",
      "calendario editorial",
      "redes sociais",
      "roteiro",
      "legenda",
      "marketing",
      "autoridade",
    ],
    fontes: [CC(7)],
  },
  {
    id: "gestor-follow-up",
    nome: "Gestor de follow-up de vendas",
    categoria: "Gestores",
    resumo:
      "Não deixa proposta sem próximo passo: cobra o vendedor ou reengaja o cliente sozinho.",
    oQueFaz:
      "Garante que nenhuma oportunidade fique sem próximo passo no CRM e reengaja propostas e orçamentos que ficaram sem resposta.",
    comoFunciona:
      "Notifica o vendedor ou dispara follow-up automatizado quando o prazo expira; ao identificar 3 dias sem retorno, resgata o contexto, envia mensagem personalizada tirando dúvidas e atualiza o status no CRM.",
    objetivo:
      "Reduzir perdas por falta de acompanhamento comercial e garantir que nenhuma oportunidade caia no esquecimento.",
    areas: ["Comercial"],
    dores: [
      "proposta enviada e esquecida",
      "vendedor não faz follow-up",
      "oportunidade perdida por silêncio",
    ],
    entregas: ["Mensagem de follow-up", "Alerta ao vendedor", "Atualização no CRM"],
    integracoes: ["CRM", "WhatsApp", "E-mail"],
    palavrasChave: [
      "follow up",
      "proposta",
      "orcamento",
      "retorno",
      "crm",
      "vendas",
      "acompanhamento",
      "reengajamento",
      "negociacao",
    ],
    fontes: [C50(26), CC(3)],
  },
  {
    id: "gestor-disparos",
    nome: "Gestor de automação de disparo de mensagens",
    categoria: "Gestores",
    resumo:
      "Administra as sequências de WhatsApp e e-mail respeitando limites de API para não tomar bloqueio.",
    oQueFaz: "Administra sequências ativas de WhatsApp e e-mail em massa.",
    comoFunciona: "Controla limites de API, intervalos e gatilhos de resposta.",
    objetivo: "Escalar a comunicação sem bloqueios por comportamento.",
    areas: ["Marketing e tráfego", "Comercial", "Atendimento"],
    dores: [
      "número bloqueado por disparo",
      "campanha em massa travando",
      "envio manual de mensagem",
    ],
    entregas: ["Disparo controlado", "Relatório de entrega"],
    integracoes: ["WhatsApp", "E-mail", "CRM"],
    palavrasChave: [
      "disparo",
      "whatsapp",
      "email marketing",
      "automacao",
      "massa",
      "bloqueio",
      "sequencia",
      "campanha",
    ],
    fontes: [C50(27)],
  },
  {
    id: "gestor-agendamentos",
    nome: "Gestor de agendamentos e blindagem de agenda",
    categoria: "Gestores",
    resumo:
      "Conversa com o lead, faz a triagem de fit e só então libera o horário na agenda do consultor.",
    oQueFaz:
      "Coordena as agendas de consultores e do time comercial e filtra reuniões antes de permitir o agendamento oficial.",
    comoFunciona:
      "Interage com o lead, faz triagem via chat para confirmar o fit, checa horários vagos, libera o calendário apenas para quem atende aos critérios mínimos e envia os convites oficiais.",
    objetivo:
      "Eliminar trocas manuais de mensagens para marcar horários e proteger o tempo dos consultores e fechadores.",
    areas: ["Comercial", "Atendimento"],
    dores: [
      "agenda cheia de reunião ruim",
      "no-show",
      "troca de mensagem infinita para marcar horário",
    ],
    entregas: ["Reunião agendada", "Convite de calendário", "Triagem do lead"],
    integracoes: ["Calendário", "WhatsApp", "CRM"],
    palavrasChave: [
      "agendamento",
      "agenda",
      "reuniao",
      "calendario",
      "no show",
      "triagem",
      "consultor",
      "horario",
      "comercial",
    ],
    fontes: [C50(28), CC(5)],
  },
  {
    id: "gestor-onboarding",
    nome: "Gestor de onboarding de clientes",
    categoria: "Gestores",
    resumo: "Conduz o cliente novo pelos primeiros passos, cobra documentos e valida cada etapa.",
    oQueFaz: "Guia novos clientes nos primeiros passos após a assinatura.",
    comoFunciona: "Envia instruções, solicita documentos e valida a conclusão de cada etapa.",
    objetivo: "Acelerar a entrega de valor inicial e reduzir o churn.",
    areas: ["Atendimento", "Operações"],
    dores: [
      "cliente novo abandonado depois da venda",
      "onboarding manual",
      "churn nos primeiros meses",
    ],
    entregas: ["Checklist de onboarding", "Mensagens guiadas", "Status por cliente"],
    integracoes: ["WhatsApp", "E-mail", "CRM"],
    palavrasChave: [
      "onboarding",
      "implantacao",
      "cliente novo",
      "pos venda",
      "ativacao",
      "churn",
      "documentos",
      "sucesso do cliente",
    ],
    fontes: [C50(29)],
  },
  {
    id: "gestor-service-desk",
    nome: "Gestor de solicitações internas (service desk RH/TI)",
    categoria: "Gestores",
    resumo: "Recebe os pedidos internos, resolve o que é simples e encaminha o resto já classificado.",
    oQueFaz: "Gerencia pedidos de suporte internos dos colaboradores.",
    comoFunciona:
      "Categoriza urgências, resolve dúvidas simples ou encaminha ao responsável.",
    objetivo: "Desafogar as equipes de suporte interno de demandas repetitivas.",
    areas: ["RH", "Operações"],
    dores: [
      "time interno interrompido o dia todo",
      "mesma dúvida repetida",
      "chamado sem triagem",
    ],
    entregas: ["Resposta automática", "Chamado categorizado"],
    integracoes: ["Chat interno", "Help desk", "E-mail"],
    palavrasChave: [
      "service desk",
      "chamado",
      "suporte interno",
      "ti",
      "rh",
      "solicitacao",
      "duvida",
      "triagem",
      "helpdesk",
    ],
    fontes: [C50(30)],
  },
  {
    id: "gestor-consolidador",
    nome: "Gestor estratégico (consolidador de dados)",
    categoria: "Gestores",
    resumo:
      "Junta vendas, tráfego, suporte e financeiro do dia em um resumo executivo para a diretoria.",
    oQueFaz: "Unifica relatórios de diferentes setores em um único sumário executivo.",
    comoFunciona:
      "Puxa dados de vendas, tráfego, suporte e financeiro ao fim do dia, sintetiza em um painel de texto claro e envia o resumo direto à diretoria.",
    objetivo: "Dar clareza total à liderança sem exigir abrir dezenas de planilhas.",
    areas: ["Diretoria", "Operações"],
    dores: [
      "dado espalhado em vários sistemas",
      "diretoria sem visão do dia",
      "relatório montado na mão",
    ],
    entregas: ["Resumo executivo diário", "Painel consolidado"],
    integracoes: ["CRM", "ERP", "Plataformas de anúncio", "Planilhas"],
    palavrasChave: [
      "relatorio",
      "resumo executivo",
      "diretoria",
      "consolidacao",
      "dados",
      "painel",
      "gestao",
      "indicadores",
      "kpi",
    ],
    fontes: [CC(16)],
  },
  {
    id: "gestor-follow-up-interno",
    nome: "Assistente de follow-up interno",
    categoria: "Gestores",
    resumo: "Cobra prazos e tarefas entre os próprios colaboradores, sem o gestor virar cobrador.",
    oQueFaz: "Cobra prazos e tarefas pendentes entre os próprios colaboradores.",
    comoFunciona:
      "Identifica prazos de reuniões (integrado ao Trello/Notion), envia lembretes gentis aos responsáveis antes do vencimento e atualiza o gestor.",
    objetivo: "Manter os projetos rodando no prazo sem que o gestor precise cobrar manualmente.",
    areas: ["Operações", "Diretoria"],
    dores: [
      "tarefa atrasada",
      "gestor virou cobrador",
      "combinado de reunião que ninguém executa",
    ],
    entregas: ["Lembrete ao responsável", "Status para o gestor"],
    integracoes: ["Trello", "Notion", "Chat interno", "Calendário"],
    palavrasChave: [
      "tarefa",
      "prazo",
      "projeto",
      "cobranca interna",
      "produtividade",
      "equipe",
      "lembrete",
      "gestao",
    ],
    fontes: [CC(22)],
  },
  {
    id: "gerador-orcamento-projeto",
    nome: "Gerador de orçamento de projetos personalizados",
    categoria: "Orçamentos e propostas",
    resumo: "Transforma escopo e prazo informados em formulário em uma estimativa de preço na hora.",
    oQueFaz: "Monta estimativas rápidas baseadas nas necessidades do cliente.",
    comoFunciona: "Processa variáveis de escopo e prazos via formulário e calcula os preços.",
    objetivo: "Entregar orçamentos iniciais ágeis para acelerar negociações.",
    areas: ["Comercial", "Financeiro"],
    dores: [
      "demora para mandar orçamento",
      "cada vendedor calcula de um jeito",
      "cliente esperando preço",
    ],
    entregas: ["Orçamento estimado", "Formulário de escopo"],
    integracoes: ["Formulários", "Planilhas", "CRM"],
    palavrasChave: [
      "orcamento",
      "estimativa",
      "preco",
      "escopo",
      "projeto",
      "proposta",
      "calculo",
      "comercial",
    ],
    fontes: [C50(31)],
  },
  {
    id: "gerador-proposta-b2b",
    nome: "Gerador de proposta comercial B2B em PDF",
    categoria: "Orçamentos e propostas",
    resumo:
      "Pega a reunião de diagnóstico e devolve a proposta formatada em PDF, pronta para enviar e assinar.",
    oQueFaz:
      "Cria a proposta comercial completa com base na reunião de diagnóstico, formatada e pronta para assinatura, sem intervenção humana.",
    comoFunciona:
      "Extrai anotações e transcrições de áudio para preencher o modelo institucional, puxa dados do cliente e valores, gera o PDF e dispara via WhatsApp com link de aceite.",
    objetivo:
      "Poupar tempo do vendedor, padronizar o material enviado e acelerar o ciclo de vendas.",
    areas: ["Comercial"],
    dores: [
      "proposta demora dias para sair",
      "cada proposta com uma cara",
      "vendedor montando PDF na mão",
    ],
    entregas: ["PDF pronto para assinatura", "Envio no WhatsApp", "Link de aceite"],
    integracoes: ["CRM", "WhatsApp", "Assinatura eletrônica", "Transcrição de áudio"],
    palavrasChave: [
      "proposta",
      "pdf",
      "comercial",
      "b2b",
      "assinatura",
      "orcamento",
      "documento",
      "fechamento",
      "vendas",
    ],
    fontes: [C50(32), CC(2)],
  },
  {
    id: "gerador-tabela-precos",
    nome: "Gerador de tabela de preços e condições especiais",
    categoria: "Orçamentos e propostas",
    resumo: "Calcula até onde o vendedor pode negociar sem furar a margem mínima da empresa.",
    oQueFaz: "Calcula descontos permitidos e parcelamentos para casos específicos.",
    comoFunciona: "Cruza a margem mínima da empresa com o volume negociado.",
    objetivo: "Dar autonomia ao vendedor sem comprometer a margem.",
    areas: ["Comercial", "Financeiro"],
    dores: [
      "desconto dado sem critério",
      "vendedor dependendo do gestor para negociar",
      "margem corroída",
    ],
    entregas: ["Tabela de condições", "Limite de desconto aprovado"],
    integracoes: ["ERP", "CRM", "Planilhas"],
    palavrasChave: [
      "desconto",
      "tabela de precos",
      "parcelamento",
      "margem",
      "negociacao",
      "condicao comercial",
      "autonomia",
      "vendedor",
    ],
    fontes: [C50(33)],
  },
  {
    id: "gerador-renovacao",
    nome: "Gerador de renovação de contratos",
    categoria: "Orçamentos e propostas",
    resumo: "Aplica IPCA/IGPM sobre o contrato original e emite o termo de reajuste na data certa.",
    oQueFaz: "Elabora termos de reajuste anual e renovações contratuais.",
    comoFunciona: "Aplica índices inflacionários (IPCA/IGPM) sobre o contrato original.",
    objetivo: "Garantir a atualização do faturamento sem atrasos operacionais.",
    areas: ["Financeiro", "Jurídico e compliance", "Comercial"],
    dores: [
      "contrato renovado sem reajuste",
      "receita defasada",
      "renovação esquecida",
    ],
    entregas: ["Termo de renovação", "Cálculo do reajuste"],
    integracoes: ["ERP", "Base de contratos", "Assinatura eletrônica"],
    palavrasChave: [
      "contrato",
      "renovacao",
      "reajuste",
      "ipca",
      "igpm",
      "aditivo",
      "faturamento",
      "recorrencia",
    ],
    fontes: [C50(34)],
  },
  {
    id: "gerador-estimativa-trafego",
    nome: "Gerador de estimativa de tráfego pago",
    categoria: "Orçamentos e propostas",
    resumo:
      "Projeta leads, custo e retorno para o orçamento que o cliente pretende investir — antes do fechamento.",
    oQueFaz: "Monta projeções de resultados de mídia baseadas em orçamento.",
    comoFunciona: "Utiliza CTRs e taxas de conversão históricas para estimar as métricas.",
    objetivo: "Demonstrar clareza de retorno antes do fechamento do contrato.",
    areas: ["Comercial", "Marketing e tráfego"],
    dores: [
      "cliente quer saber quanto vai retornar",
      "promessa de resultado no chute",
      "proposta de tráfego sem números",
    ],
    entregas: ["Projeção de resultados", "Cenários de investimento"],
    integracoes: ["Meta Ads", "Google Ads", "Histórico de campanhas"],
    palavrasChave: [
      "estimativa",
      "projecao",
      "trafego pago",
      "midia",
      "roi",
      "orcamento",
      "proposta",
      "leads",
      "previsao",
    ],
    fontes: [C50(35)],
  },
  {
    id: "pdf-contrato",
    nome: "Gerador de contrato de serviço final em PDF",
    categoria: "Documentos em PDF",
    resumo: "Compila dados cadastrais e escopo aprovado no modelo jurídico e devolve o PDF para assinar.",
    oQueFaz: "Compila dados cadastrais e o escopo aprovado em um PDF pronto para assinar.",
    comoFunciona: "Preenche as variáveis no modelo jurídico oficial e converte em documento.",
    objetivo: "Agilizar o envio de contratos via plataformas de assinatura.",
    areas: ["Jurídico e compliance", "Comercial"],
    dores: [
      "contrato montado manualmente",
      "erro de digitação em cláusula",
      "demora entre aceite e assinatura",
    ],
    entregas: ["Contrato em PDF", "Envio para assinatura"],
    integracoes: ["Assinatura eletrônica", "CRM", "Modelos jurídicos"],
    palavrasChave: [
      "contrato",
      "pdf",
      "juridico",
      "assinatura",
      "documento",
      "clausula",
      "fechamento",
      "cadastro",
    ],
    fontes: [C50(36)],
  },
  {
    id: "pdf-relatorio-trafego",
    nome: "Gerador de relatório de tráfego pago em PDF",
    categoria: "Documentos em PDF",
    resumo: "Fecha o mês de campanhas em um relatório visual com gráficos e diagnóstico, sozinho.",
    oQueFaz: "Consolida os resultados mensais de campanhas em um relatório visual.",
    comoFunciona: "Coleta métricas de APIs, adiciona gráficos e diagnósticos em PDF.",
    objetivo: "Reduzir em 90% a montagem manual de relatórios mensais.",
    areas: ["Marketing e tráfego", "Diretoria"],
    dores: [
      "relatório mensal consome dias",
      "cliente cobrando resultado",
      "print de plataforma colado em slide",
    ],
    entregas: ["Relatório em PDF", "Gráficos e diagnóstico"],
    integracoes: ["Meta Ads", "Google Ads", "Google Analytics"],
    palavrasChave: [
      "relatorio",
      "pdf",
      "trafego pago",
      "campanha",
      "mensal",
      "agencia",
      "cliente",
      "metricas",
      "dashboard",
    ],
    fontes: [C50(37)],
  },
  {
    id: "pdf-dre",
    nome: "Gerador de faturas e DRE operacional",
    categoria: "Documentos em PDF",
    resumo:
      "Organiza entradas e saídas em linhas contábeis e entrega a DRE do mês formatada para a diretoria.",
    oQueFaz:
      "Consolida recebimentos e despesas do mês em demonstrativo formal e organiza dados financeiros brutos em demonstrativos contábeis claros.",
    comoFunciona:
      "Organiza entradas e saídas bancárias em linhas contábeis, categoriza custos fixos, variáveis e impostos, e monta a DRE formatada em PDF.",
    objetivo:
      "Facilitar a tomada de decisão financeira da diretoria e o fechamento de mês, com visibilidade da saúde do negócio.",
    areas: ["Financeiro", "Diretoria"],
    dores: [
      "fechamento de mês demorado",
      "não saber o lucro real",
      "financeiro só em planilha",
    ],
    entregas: ["DRE em PDF", "Faturas", "Relatório financeiro"],
    integracoes: ["ERP", "Extrato bancário", "Planilhas"],
    palavrasChave: [
      "dre",
      "financeiro",
      "fatura",
      "contabil",
      "fechamento",
      "custo",
      "lucro",
      "demonstrativo",
      "caixa",
    ],
    fontes: [C50(38), CC(20)],
  },
  {
    id: "pdf-manual-onboarding",
    nome: "Gerador de manual de onboarding em PDF",
    categoria: "Documentos em PDF",
    resumo: "Cria o guia de boas-vindas personalizado para cada novo colaborador ou cliente.",
    oQueFaz: "Cria um guia exclusivo para novos colaboradores ou clientes.",
    comoFunciona: null,
    objetivo: "Profissionalizar a recepção de novos integrantes na operação.",
    areas: ["RH", "Operações", "Atendimento"],
    dores: [
      "onboarding informal e improvisado",
      "material de boas-vindas desatualizado",
      "cada novo integrante aprende de um jeito",
    ],
    entregas: ["Manual em PDF"],
    integracoes: ["Base de processos internos"],
    palavrasChave: [
      "manual",
      "onboarding",
      "pdf",
      "treinamento",
      "boas vindas",
      "colaborador",
      "cliente novo",
      "documentacao",
    ],
    fontes: [C50(39)],
  },
  {
    id: "pdf-midia-kit",
    nome: "Gerador de mídia kit de prospecção",
    categoria: "Documentos em PDF",
    resumo: "Mantém o material institucional sempre atualizado com os cases e métricas mais recentes.",
    oQueFaz: "Gera um PDF institucional atualizado com cases de sucesso recentes.",
    comoFunciona: "Insere avaliações e métricas atualizadas no template da marca.",
    objetivo: "Impactar prospects com material comercial sempre atualizado.",
    areas: ["Comercial", "Marketing e tráfego"],
    dores: [
      "apresentação institucional velha",
      "case desatualizado na proposta",
      "material comercial refeito toda hora",
    ],
    entregas: ["Mídia kit em PDF", "Cases atualizados"],
    integracoes: ["CRM", "Base de cases", "Template da marca"],
    palavrasChave: [
      "midia kit",
      "institucional",
      "prospeccao",
      "apresentacao",
      "case",
      "portfolio",
      "pdf",
      "marca",
    ],
    fontes: [C50(40)],
  },
  {
    id: "concorrencia-anuncios",
    nome: "Monitor de anúncios de concorrentes",
    categoria: "Concorrência",
    resumo: "Acompanha os criativos e ofertas que os rivais estão rodando nas bibliotecas de anúncios.",
    oQueFaz: "Acompanha criativos e ofertas que rivais rodam nas redes sociais.",
    comoFunciona: "Varre bibliotecas de anúncios buscando cópias e formatos novos.",
    objetivo: "Identificar tendências e manter ofertas altamente competitivas.",
    areas: ["Marketing e tráfego", "Comercial"],
    dores: [
      "concorrente anunciando melhor",
      "oferta desatualizada",
      "falta de referência de criativo",
    ],
    entregas: ["Painel de anúncios rivais", "Alerta de nova oferta"],
    integracoes: ["Biblioteca de anúncios Meta", "Redes sociais"],
    palavrasChave: [
      "concorrente",
      "anuncio",
      "criativo",
      "oferta",
      "biblioteca de anuncios",
      "benchmark",
      "mercado",
      "trafego",
    ],
    fontes: [C50(41)],
  },
  {
    id: "concorrencia-precos",
    nome: "Rastreador de mudanças de preço do mercado",
    categoria: "Concorrência",
    resumo: "Avisa no mesmo dia em que um concorrente direto mexe no preço ou lança promoção.",
    oQueFaz:
      "Alerta quando concorrentes diretos alteram preços de serviços e monitora movimentações de ofertas do mercado.",
    comoFunciona:
      "Checa landing pages e sites da concorrência periodicamente e compila as mudanças em relatório semanal, apontando descontos e novos produtos.",
    objetivo:
      "Evitar perda de vendas por desalinhamento mercadológico e nunca ser pego desprevenido por mudanças de mercado.",
    areas: ["Comercial", "Marketing e tráfego", "Diretoria"],
    dores: [
      "perder venda por preço",
      "não saber o que o concorrente cobra",
      "promoção do rival descoberta tarde",
    ],
    entregas: ["Alerta de mudança de preço", "Relatório semanal de mercado"],
    integracoes: ["Web scraping", "Sites de concorrentes"],
    palavrasChave: [
      "concorrencia",
      "preco",
      "mercado",
      "promocao",
      "benchmark",
      "monitoramento",
      "oferta",
      "competitividade",
    ],
    fontes: [C50(42), CC(11)],
  },
  {
    id: "concorrencia-seo",
    nome: "Analista de SEO e palavras-chave",
    categoria: "Concorrência",
    resumo: "Descobre em quais buscas os concorrentes aparecem e onde dá para ultrapassar no orgânico.",
    oQueFaz: "Descobre termos de busca em que concorrentes ranqueiam no Google.",
    comoFunciona: null,
    objetivo: "Posicionar a marca à frente da concorrência no orgânico.",
    areas: ["Marketing e tráfego"],
    dores: [
      "site sem tráfego orgânico",
      "concorrente na frente no Google",
      "não saber que palavra atacar",
    ],
    entregas: ["Lista de palavras-chave", "Diagnóstico de SEO"],
    integracoes: ["Google", "Ferramentas de SEO"],
    palavrasChave: [
      "seo",
      "google",
      "palavra chave",
      "organico",
      "busca",
      "ranqueamento",
      "site",
      "conteudo",
      "concorrente",
    ],
    fontes: [C50(43)],
  },
  {
    id: "concorrencia-vagas",
    nome: "Mapeador de vagas e expansão de concorrentes",
    categoria: "Concorrência",
    resumo: "Lê as vagas que os rivais abriram para antecipar em que eles vão apostar.",
    oQueFaz: "Monitora contratações de concorrentes para antecipar movimentos.",
    comoFunciona: "Analisa vagas de trabalho abertas por rivais em portais de RH.",
    objetivo: "Identificar novos nichos ou serviços planejados pelo rival.",
    areas: ["Diretoria", "Comercial"],
    dores: [
      "concorrente lançando serviço novo de surpresa",
      "falta de leitura de movimento de mercado",
    ],
    entregas: ["Alerta de movimento", "Relatório de expansão"],
    integracoes: ["Portais de vagas", "LinkedIn"],
    palavrasChave: [
      "concorrente",
      "vagas",
      "expansao",
      "mercado",
      "estrategia",
      "movimento",
      "inteligencia competitiva",
    ],
    fontes: [C50(44)],
  },
  {
    id: "concorrencia-swot",
    nome: "Analista SWOT da concorrência (espião local)",
    categoria: "Concorrência",
    resumo:
      "Lê as avaliações públicas dos rivais e transforma a reclamação deles em argumento de venda seu.",
    oQueFaz:
      "Mapeia forças e fraquezas com base em reviews públicos de rivais e analisa avaliações de concorrentes locais no Google Meu Negócio.",
    comoFunciona:
      "Coleta avaliações do Google Meu Negócio e do Reclame Aqui na mesma região, identifica as principais reclamações (demora, preço alto) e sugere ganchos de marketing.",
    objetivo:
      "Usar os pontos fracos dos rivais como argumento de vendas e capturar clientes insatisfeitos da concorrência.",
    areas: ["Comercial", "Marketing e tráfego"],
    dores: [
      "falta de argumento contra o concorrente",
      "disputa local acirrada",
      "não saber por que o cliente prefere o rival",
    ],
    entregas: ["Análise SWOT", "Ganchos de campanha"],
    integracoes: ["Google Meu Negócio", "Reclame Aqui", "Web scraping"],
    palavrasChave: [
      "swot",
      "concorrencia",
      "review",
      "avaliacao",
      "local",
      "google meu negocio",
      "reclame aqui",
      "argumento de venda",
      "diferencial",
    ],
    fontes: [C50(45), CC(12)],
  },
  {
    id: "sdr-whatsapp",
    nome: "Qualificador e atendente inicial no WhatsApp (SDR de IA)",
    categoria: "Conteúdo e prospecção",
    resumo:
      "Atende o lead no primeiro segundo, faz as perguntas de qualificação, pontua e agenda com o vendedor.",
    oQueFaz:
      "Conversa com leads de tráfego pago qualificando necessidades e faz a triagem e a pontuação inicial de quem chega pelo WhatsApp ou pelo site.",
    comoFunciona:
      "Executa perguntas-chave sobre orçamento e urgência, calcula uma nota, classifica o lead antes de passar ao humano e, se qualificado, agenda a reunião no calendário do vendedor.",
    objetivo:
      "Garantir atendimento imediato, filtrar curiosos e fazer o time comercial focar apenas em quem tem potencial real de compra.",
    areas: ["Comercial", "Atendimento", "Marketing e tráfego"],
    dores: [
      "lead sem resposta imediata",
      "vendedor perdendo tempo com curioso",
      "atendimento fora do horário comercial",
      "muito lead e pouco time",
    ],
    entregas: ["Lead qualificado com nota", "Reunião agendada", "Registro no CRM"],
    integracoes: ["WhatsApp", "CRM", "Calendário", "Site"],
    palavrasChave: [
      "whatsapp",
      "sdr",
      "qualificacao",
      "lead",
      "atendimento",
      "chatbot",
      "triagem",
      "agendamento",
      "prospeccao",
      "comercial",
      "24 horas",
    ],
    fontes: [C50(46), CC(1)],
  },
  {
    id: "redator-anuncios",
    nome: "Redator de anúncios (copywriter para tráfego)",
    categoria: "Conteúdo e prospecção",
    resumo: "Escreve variações de copy em frameworks validados para alimentar testes A/B de mídia.",
    oQueFaz: "Cria múltiplos textos persuasivos para testes A/B em mídia paga.",
    comoFunciona: "Utiliza frameworks validados (AIDA, PAS) focando nas dores do público.",
    objetivo: "Elevar as taxas de clique (CTR) e reduzir custos de conversão.",
    areas: ["Marketing e tráfego"],
    dores: [
      "criativo cansado",
      "poucas variações para testar",
      "CTR baixo",
      "redator sobrecarregado",
    ],
    entregas: ["Variações de copy", "Textos para teste A/B"],
    integracoes: ["Meta Ads", "Google Ads"],
    palavrasChave: [
      "copy",
      "anuncio",
      "criativo",
      "teste ab",
      "texto",
      "ctr",
      "redacao",
      "trafego pago",
      "persuasao",
    ],
    fontes: [C50(47)],
  },
  {
    id: "avaliador-copy",
    nome: "Avaliador de copy",
    categoria: "Conteúdo e prospecção",
    resumo: "Dá nota e sugestões ao texto antes de ele ir ao ar — e evita bloqueio de plataforma.",
    oQueFaz: "Analisa textos de anúncios e e-mails antes de irem ao ar.",
    comoFunciona:
      "O redator envia o texto, a IA cruza com frameworks de persuasão e regras das plataformas e retorna nota e sugestões de melhoria.",
    objetivo:
      "Elevar a taxa de conversão dos textos e reduzir riscos de bloqueio em plataformas.",
    areas: ["Marketing e tráfego"],
    dores: [
      "anúncio reprovado pela plataforma",
      "texto sem conversão",
      "revisão de copy manual",
    ],
    entregas: ["Nota do texto", "Sugestões de melhoria"],
    integracoes: ["Meta Ads", "Google Ads", "E-mail marketing"],
    palavrasChave: [
      "copy",
      "revisao",
      "anuncio",
      "bloqueio",
      "politica de anuncios",
      "conversao",
      "texto",
      "email",
      "qualidade",
    ],
    fontes: [CC(9)],
  },
  {
    id: "emails-nutricao",
    nome: "Criador de e-mails de nutrição e vendas",
    categoria: "Conteúdo e prospecção",
    resumo: "Escreve as sequências completas de e-mail que mantêm o lead aquecido até a hora de fechar.",
    oQueFaz: "Escreve sequências completas de e-mails para nutrir leads.",
    comoFunciona: null,
    objetivo: "Manter o engajamento até o momento ideal de fechamento.",
    areas: ["Marketing e tráfego", "Comercial"],
    dores: [
      "lead esfria entre o cadastro e a venda",
      "nenhuma nutrição rodando",
      "e-mail marketing parado",
    ],
    entregas: ["Sequência de e-mails", "Fluxo de nutrição"],
    integracoes: ["E-mail marketing", "CRM"],
    palavrasChave: [
      "email",
      "nutricao",
      "fluxo",
      "automacao",
      "lead",
      "engajamento",
      "sequencia",
      "marketing",
      "conversao",
    ],
    fontes: [C50(48)],
  },
  {
    id: "leitor-documentos",
    nome: "Leitor e transcritor de documentos (OCR)",
    categoria: "Conteúdo e prospecção",
    resumo:
      "Transforma contrato, fatura e recibo em dado estruturado dentro do sistema, sem digitação.",
    oQueFaz:
      "Transforma contratos legados, faturas e recibos em texto estruturado e cataloga informações de documentos não estruturados.",
    comoFunciona:
      "Extrai dados de imagens e PDFs, identifica cláusulas, valores e prazos e insere as informações direto no banco de dados ou no ERP.",
    objetivo:
      "Eliminar a digitação manual, reduzir erros humanos e organizar o acervo histórico.",
    areas: ["Operações", "Financeiro", "Jurídico e compliance"],
    dores: [
      "digitação manual de documento",
      "contrato só em papel ou PDF",
      "erro de lançamento",
      "acervo desorganizado",
    ],
    entregas: ["Dados estruturados no sistema", "Documento indexado"],
    integracoes: ["OCR", "ERP", "Banco de dados"],
    palavrasChave: [
      "ocr",
      "documento",
      "pdf",
      "contrato",
      "fatura",
      "digitalizacao",
      "extracao",
      "erp",
      "cadastro",
      "transcricao",
    ],
    fontes: [C50(49), CC(13)],
  },
  {
    id: "redator-outbound",
    nome: "Redator de prospecção fria (outbound)",
    categoria: "Conteúdo e prospecção",
    resumo:
      "Pesquisa o prospect e escreve a abordagem personalizada que faz o decisor B2B responder.",
    oQueFaz: "Escreve mensagens customizadas para abordagem de decisores B2B.",
    comoFunciona: "Pesquisa dados públicos do prospect inserindo ganchos personalizados.",
    objetivo: "Maximizar a taxa de resposta e o agendamento de reuniões.",
    areas: ["Comercial"],
    dores: [
      "cold call e cold mail sem resposta",
      "mensagem genérica",
      "prospecção ativa travada",
    ],
    entregas: ["Mensagem personalizada", "Lista de abordagens"],
    integracoes: ["LinkedIn", "E-mail", "CRM", "Fontes públicas"],
    palavrasChave: [
      "outbound",
      "prospeccao",
      "cold mail",
      "b2b",
      "abordagem",
      "decisor",
      "mensagem",
      "linkedin",
      "resposta",
    ],
    fontes: [C50(50)],
  },
  {
    id: "reciclador-midia",
    nome: "Reciclador de mídia",
    categoria: "Conteúdo e prospecção",
    resumo: "Pega um conteúdo longo e devolve dezenas de cortes, threads e carrosséis.",
    oQueFaz: "Transforma conteúdos longos em múltiplos formatos curtos.",
    comoFunciona:
      "Você envia a transcrição do podcast ou vídeo, a IA extrai os melhores trechos e formata em threads, carrosséis e roteiros curtos.",
    objetivo: "Multiplicar o alcance de um único esforço de produção de conteúdo.",
    areas: ["Marketing e tráfego"],
    dores: [
      "produzir conteúdo toda semana",
      "material bom que morre em um único post",
      "custo alto de produção",
    ],
    entregas: ["Cortes e roteiros", "Threads e carrosséis"],
    integracoes: ["Redes sociais", "Transcrição de áudio e vídeo"],
    palavrasChave: [
      "conteudo",
      "video",
      "podcast",
      "corte",
      "reels",
      "carrossel",
      "thread",
      "reaproveitamento",
      "alcance",
      "social media",
    ],
    fontes: [CC(8)],
  },
];
